/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AssociationLoginRouteImport } from './routes/association-login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LegalRouteRouteImport } from './routes/legal.route'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedRepRouteRouteImport } from './routes/_authenticated/rep/route'
import { Route as AuthenticatedRunnerRouteRouteImport } from './routes/_authenticated/runner/route'
import { Route as AuthenticatedSuperadminRouteRouteImport } from './routes/_authenticated/superadmin/route'
import { Route as AssociationsIndexRouteImport } from './routes/associations.index'
import { Route as LegalAssociationVerificationRouteImport } from './routes/legal.association-verification'
import { Route as LegalComplianceRouteImport } from './routes/legal.compliance'
import { Route as LegalPaymentRouteImport } from './routes/legal.payment'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalQrVerificationRouteImport } from './routes/legal.qr-verification'
import { Route as LegalRefundRouteImport } from './routes/legal.refund'
import { Route as LegalSecurityRouteImport } from './routes/legal.security'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as VerifyIndexRouteImport } from './routes/verify.index'
import { Route as VerifyTokenRouteImport } from './routes/verify.$token'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminFacultiesRouteImport } from './routes/_authenticated/admin/faculties'
import { Route as AuthenticatedAdminPageHealthRouteImport } from './routes/_authenticated/admin/page-health'
import { Route as AuthenticatedAdminPaymentRequestsRouteImport } from './routes/_authenticated/admin/payment-requests'
import { Route as AuthenticatedAdminQrCodesRouteImport } from './routes/_authenticated/admin/qr-codes'
import { Route as AuthenticatedAdminReconcileRouteImport } from './routes/_authenticated/admin/reconcile'
import { Route as AuthenticatedAdminRunnersRouteImport } from './routes/_authenticated/admin/runners'
import { Route as AuthenticatedAdminSettlementsRouteImport } from './routes/_authenticated/admin/settlements'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin/students'
import { Route as AuthenticatedAdminTransactionsRouteImport } from './routes/_authenticated/admin/transactions'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAssociationSlugRouteRouteImport } from './routes/_authenticated/association/$slug/route'
import { Route as AuthenticatedAssociationsNewRouteImport } from './routes/_authenticated/associations/new'
import { Route as AuthenticatedPayRequestIdRouteImport } from './routes/_authenticated/pay.$requestId'
import { Route as AuthenticatedReceiptTokenRouteImport } from './routes/_authenticated/receipt.$token'
import { Route as AuthenticatedRepIndexRouteImport } from './routes/_authenticated/rep/index'
import { Route as AuthenticatedRunnerIndexRouteImport } from './routes/_authenticated/runner/index'
import { Route as AuthenticatedSuperadminIndexRouteImport } from './routes/_authenticated/superadmin/index'
import { Route as AuthenticatedSuperadminActivityRouteImport } from './routes/_authenticated/superadmin/activity'
import { Route as AuthenticatedSuperadminAssociationsRouteImport } from './routes/_authenticated/superadmin/associations'
import { Route as AuthenticatedSuperadminBankVerificationsRouteImport } from './routes/_authenticated/superadmin/bank-verifications'
import { Route as AuthenticatedSuperadminNominationsRouteImport } from './routes/_authenticated/superadmin/nominations'
import { Route as AuthenticatedSuperadminUsersRouteImport } from './routes/_authenticated/superadmin/users'
import { Route as AuthenticatedAssociationSlugIndexRouteImport } from './routes/_authenticated/association/$slug/index'
import { Route as AuthenticatedAssociationSlugApprovalsRouteImport } from './routes/_authenticated/association/$slug/approvals'
import { Route as AuthenticatedAssociationSlugAuditRouteImport } from './routes/_authenticated/association/$slug/audit'
import { Route as AuthenticatedAssociationSlugBankRouteImport } from './routes/_authenticated/association/$slug/bank'
import { Route as AuthenticatedAssociationSlugDuesRouteImport } from './routes/_authenticated/association/$slug/dues'
import { Route as AuthenticatedAssociationSlugExecutivesRouteImport } from './routes/_authenticated/association/$slug/executives'
import { Route as AuthenticatedAssociationSlugFinanceRouteImport } from './routes/_authenticated/association/$slug/finance'
import { Route as AuthenticatedAssociationSlugMembersRouteImport } from './routes/_authenticated/association/$slug/members'
import { Route as AuthenticatedAssociationSlugPaymentLinksRouteImport } from './routes/_authenticated/association/$slug/payment-links'
import { Route as AuthenticatedSuperadminAssociationIdRouteImport } from './routes/_authenticated/superadmin/association.$id'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api/public/webhooks/paystack'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociationLoginRoute = AssociationLoginRouteImport.update({
  id: '/association-login',
  path: '/association-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRouteRoute = LegalRouteRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepRouteRoute = AuthenticatedRepRouteRouteImport.update({
  id: '/rep',
  path: '/rep',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRunnerRouteRoute =
  AuthenticatedRunnerRouteRouteImport.update({
    id: '/runner',
    path: '/runner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperadminRouteRoute =
  AuthenticatedSuperadminRouteRouteImport.update({
    id: '/superadmin',
    path: '/superadmin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AssociationsIndexRoute = AssociationsIndexRouteImport.update({
  id: '/associations/',
  path: '/associations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAssociationVerificationRoute =
  LegalAssociationVerificationRouteImport.update({
    id: '/association-verification',
    path: '/association-verification',
    getParentRoute: () => LegalRouteRoute,
  } as any)
const LegalComplianceRoute = LegalComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalPaymentRoute = LegalPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalQrVerificationRoute = LegalQrVerificationRouteImport.update({
  id: '/qr-verification',
  path: '/qr-verification',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalSecurityRoute = LegalSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRouteRoute,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminFacultiesRoute =
  AuthenticatedAdminFacultiesRouteImport.update({
    id: '/faculties',
    path: '/faculties',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPageHealthRoute =
  AuthenticatedAdminPageHealthRouteImport.update({
    id: '/page-health',
    path: '/page-health',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentRequestsRoute =
  AuthenticatedAdminPaymentRequestsRouteImport.update({
    id: '/payment-requests',
    path: '/payment-requests',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQrCodesRoute =
  AuthenticatedAdminQrCodesRouteImport.update({
    id: '/qr-codes',
    path: '/qr-codes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReconcileRoute =
  AuthenticatedAdminReconcileRouteImport.update({
    id: '/reconcile',
    path: '/reconcile',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRunnersRoute =
  AuthenticatedAdminRunnersRouteImport.update({
    id: '/runners',
    path: '/runners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettlementsRoute =
  AuthenticatedAdminSettlementsRouteImport.update({
    id: '/settlements',
    path: '/settlements',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTransactionsRoute =
  AuthenticatedAdminTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAssociationSlugRouteRoute =
  AuthenticatedAssociationSlugRouteRouteImport.update({
    id: '/association/$slug',
    path: '/association/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssociationsNewRoute =
  AuthenticatedAssociationsNewRouteImport.update({
    id: '/associations/new',
    path: '/associations/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayRequestIdRoute =
  AuthenticatedPayRequestIdRouteImport.update({
    id: '/pay/$requestId',
    path: '/pay/$requestId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceiptTokenRoute =
  AuthenticatedReceiptTokenRouteImport.update({
    id: '/receipt/$token',
    path: '/receipt/$token',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRepIndexRoute = AuthenticatedRepIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRepRouteRoute,
} as any)
const AuthenticatedRunnerIndexRoute =
  AuthenticatedRunnerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRunnerRouteRoute,
  } as any)
const AuthenticatedSuperadminIndexRoute =
  AuthenticatedSuperadminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuperadminRouteRoute,
  } as any)
const AuthenticatedSuperadminActivityRoute =
  AuthenticatedSuperadminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedSuperadminRouteRoute,
  } as any)
const AuthenticatedSuperadminAssociationsRoute =
  AuthenticatedSuperadminAssociationsRouteImport.update({
    id: '/associations',
    path: '/associations',
    getParentRoute: () => AuthenticatedSuperadminRouteRoute,
  } as any)
const AuthenticatedSuperadminBankVerificationsRoute =
  AuthenticatedSuperadminBankVerificationsRouteImport.update({
    id: '/bank-verifications',
    path: '/bank-verifications',
    getParentRoute: () => AuthenticatedSuperadminRouteRoute,
  } as any)
const AuthenticatedSuperadminNominationsRoute =
  AuthenticatedSuperadminNominationsRouteImport.update({
    id: '/nominations',
    path: '/nominations',
    getParentRoute: () => AuthenticatedSuperadminRouteRoute,
  } as any)
const AuthenticatedSuperadminUsersRoute =
  AuthenticatedSuperadminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSuperadminRouteRoute,
  } as any)
const AuthenticatedAssociationSlugIndexRoute =
  AuthenticatedAssociationSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAssociationSlugRouteRoute,
  } as any)
const AuthenticatedAssociationSlugApprovalsRoute =
  AuthenticatedAssociationSlugApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedAssociationSlugRouteRoute,
  } as any)
const AuthenticatedAssociationSlugAuditRoute =
  AuthenticatedAssociationSlugAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedAssociationSlugRouteRoute,
  } as any)
const AuthenticatedAssociationSlugBankRoute =
  AuthenticatedAssociationSlugBankRouteImport.update({
    id: '/bank',
    path: '/bank',
    getParentRoute: () => AuthenticatedAssociationSlugRouteRoute,
  } as any)
const AuthenticatedAssociationSlugDuesRoute =
  AuthenticatedAssociationSlugDuesRouteImport.update({
    id: '/dues',
    path: '/dues',
    getParentRoute: () => AuthenticatedAssociationSlugRouteRoute,
  } as any)
const AuthenticatedAssociationSlugExecutivesRoute =
  AuthenticatedAssociationSlugExecutivesRouteImport.update({
    id: '/executives',
    path: '/executives',
    getParentRoute: () => AuthenticatedAssociationSlugRouteRoute,
  } as any)
const AuthenticatedAssociationSlugFinanceRoute =
  AuthenticatedAssociationSlugFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAssociationSlugRouteRoute,
  } as any)
const AuthenticatedAssociationSlugMembersRoute =
  AuthenticatedAssociationSlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAssociationSlugRouteRoute,
  } as any)
const AuthenticatedAssociationSlugPaymentLinksRoute =
  AuthenticatedAssociationSlugPaymentLinksRouteImport.update({
    id: '/payment-links',
    path: '/payment-links',
    getParentRoute: () => AuthenticatedAssociationSlugRouteRoute,
  } as any)
const AuthenticatedSuperadminAssociationIdRoute =
  AuthenticatedSuperadminAssociationIdRouteImport.update({
    id: '/association/$id',
    path: '/association/$id',
    getParentRoute: () => AuthenticatedSuperadminRouteRoute,
  } as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteRouteWithChildren
  '/association-login': typeof AssociationLoginRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/rep': typeof AuthenticatedRepRouteRouteWithChildren
  '/runner': typeof AuthenticatedRunnerRouteRouteWithChildren
  '/superadmin': typeof AuthenticatedSuperadminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/legal/association-verification': typeof LegalAssociationVerificationRoute
  '/legal/compliance': typeof LegalComplianceRoute
  '/legal/payment': typeof LegalPaymentRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/qr-verification': typeof LegalQrVerificationRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/security': typeof LegalSecurityRoute
  '/legal/terms': typeof LegalTermsRoute
  '/p/$token': typeof PTokenRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/associations/': typeof AssociationsIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/association/$slug': typeof AuthenticatedAssociationSlugRouteRouteWithChildren
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/faculties': typeof AuthenticatedAdminFacultiesRoute
  '/admin/page-health': typeof AuthenticatedAdminPageHealthRoute
  '/admin/payment-requests': typeof AuthenticatedAdminPaymentRequestsRoute
  '/admin/qr-codes': typeof AuthenticatedAdminQrCodesRoute
  '/admin/reconcile': typeof AuthenticatedAdminReconcileRoute
  '/admin/runners': typeof AuthenticatedAdminRunnersRoute
  '/admin/settlements': typeof AuthenticatedAdminSettlementsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/associations/new': typeof AuthenticatedAssociationsNewRoute
  '/pay/$requestId': typeof AuthenticatedPayRequestIdRoute
  '/receipt/$token': typeof AuthenticatedReceiptTokenRoute
  '/superadmin/activity': typeof AuthenticatedSuperadminActivityRoute
  '/superadmin/associations': typeof AuthenticatedSuperadminAssociationsRoute
  '/superadmin/bank-verifications': typeof AuthenticatedSuperadminBankVerificationsRoute
  '/superadmin/nominations': typeof AuthenticatedSuperadminNominationsRoute
  '/superadmin/users': typeof AuthenticatedSuperadminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/rep/': typeof AuthenticatedRepIndexRoute
  '/runner/': typeof AuthenticatedRunnerIndexRoute
  '/superadmin/': typeof AuthenticatedSuperadminIndexRoute
  '/association/$slug/approvals': typeof AuthenticatedAssociationSlugApprovalsRoute
  '/association/$slug/audit': typeof AuthenticatedAssociationSlugAuditRoute
  '/association/$slug/bank': typeof AuthenticatedAssociationSlugBankRoute
  '/association/$slug/dues': typeof AuthenticatedAssociationSlugDuesRoute
  '/association/$slug/executives': typeof AuthenticatedAssociationSlugExecutivesRoute
  '/association/$slug/finance': typeof AuthenticatedAssociationSlugFinanceRoute
  '/association/$slug/members': typeof AuthenticatedAssociationSlugMembersRoute
  '/association/$slug/payment-links': typeof AuthenticatedAssociationSlugPaymentLinksRoute
  '/superadmin/association/$id': typeof AuthenticatedSuperadminAssociationIdRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/association/$slug/': typeof AuthenticatedAssociationSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteRouteWithChildren
  '/association-login': typeof AssociationLoginRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/legal/association-verification': typeof LegalAssociationVerificationRoute
  '/legal/compliance': typeof LegalComplianceRoute
  '/legal/payment': typeof LegalPaymentRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/qr-verification': typeof LegalQrVerificationRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/security': typeof LegalSecurityRoute
  '/legal/terms': typeof LegalTermsRoute
  '/p/$token': typeof PTokenRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/associations': typeof AssociationsIndexRoute
  '/verify': typeof VerifyIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/faculties': typeof AuthenticatedAdminFacultiesRoute
  '/admin/page-health': typeof AuthenticatedAdminPageHealthRoute
  '/admin/payment-requests': typeof AuthenticatedAdminPaymentRequestsRoute
  '/admin/qr-codes': typeof AuthenticatedAdminQrCodesRoute
  '/admin/reconcile': typeof AuthenticatedAdminReconcileRoute
  '/admin/runners': typeof AuthenticatedAdminRunnersRoute
  '/admin/settlements': typeof AuthenticatedAdminSettlementsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/associations/new': typeof AuthenticatedAssociationsNewRoute
  '/pay/$requestId': typeof AuthenticatedPayRequestIdRoute
  '/receipt/$token': typeof AuthenticatedReceiptTokenRoute
  '/superadmin/activity': typeof AuthenticatedSuperadminActivityRoute
  '/superadmin/associations': typeof AuthenticatedSuperadminAssociationsRoute
  '/superadmin/bank-verifications': typeof AuthenticatedSuperadminBankVerificationsRoute
  '/superadmin/nominations': typeof AuthenticatedSuperadminNominationsRoute
  '/superadmin/users': typeof AuthenticatedSuperadminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/rep': typeof AuthenticatedRepIndexRoute
  '/runner': typeof AuthenticatedRunnerIndexRoute
  '/superadmin': typeof AuthenticatedSuperadminIndexRoute
  '/association/$slug/approvals': typeof AuthenticatedAssociationSlugApprovalsRoute
  '/association/$slug/audit': typeof AuthenticatedAssociationSlugAuditRoute
  '/association/$slug/bank': typeof AuthenticatedAssociationSlugBankRoute
  '/association/$slug/dues': typeof AuthenticatedAssociationSlugDuesRoute
  '/association/$slug/executives': typeof AuthenticatedAssociationSlugExecutivesRoute
  '/association/$slug/finance': typeof AuthenticatedAssociationSlugFinanceRoute
  '/association/$slug/members': typeof AuthenticatedAssociationSlugMembersRoute
  '/association/$slug/payment-links': typeof AuthenticatedAssociationSlugPaymentLinksRoute
  '/superadmin/association/$id': typeof AuthenticatedSuperadminAssociationIdRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/association/$slug': typeof AuthenticatedAssociationSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/legal': typeof LegalRouteRouteWithChildren
  '/association-login': typeof AssociationLoginRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/rep': typeof AuthenticatedRepRouteRouteWithChildren
  '/_authenticated/runner': typeof AuthenticatedRunnerRouteRouteWithChildren
  '/_authenticated/superadmin': typeof AuthenticatedSuperadminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/legal/association-verification': typeof LegalAssociationVerificationRoute
  '/legal/compliance': typeof LegalComplianceRoute
  '/legal/payment': typeof LegalPaymentRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/qr-verification': typeof LegalQrVerificationRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/security': typeof LegalSecurityRoute
  '/legal/terms': typeof LegalTermsRoute
  '/p/$token': typeof PTokenRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/associations/': typeof AssociationsIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/_authenticated/association/$slug': typeof AuthenticatedAssociationSlugRouteRouteWithChildren
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/faculties': typeof AuthenticatedAdminFacultiesRoute
  '/_authenticated/admin/page-health': typeof AuthenticatedAdminPageHealthRoute
  '/_authenticated/admin/payment-requests': typeof AuthenticatedAdminPaymentRequestsRoute
  '/_authenticated/admin/qr-codes': typeof AuthenticatedAdminQrCodesRoute
  '/_authenticated/admin/reconcile': typeof AuthenticatedAdminReconcileRoute
  '/_authenticated/admin/runners': typeof AuthenticatedAdminRunnersRoute
  '/_authenticated/admin/settlements': typeof AuthenticatedAdminSettlementsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/associations/new': typeof AuthenticatedAssociationsNewRoute
  '/_authenticated/pay/$requestId': typeof AuthenticatedPayRequestIdRoute
  '/_authenticated/receipt/$token': typeof AuthenticatedReceiptTokenRoute
  '/_authenticated/superadmin/activity': typeof AuthenticatedSuperadminActivityRoute
  '/_authenticated/superadmin/associations': typeof AuthenticatedSuperadminAssociationsRoute
  '/_authenticated/superadmin/bank-verifications': typeof AuthenticatedSuperadminBankVerificationsRoute
  '/_authenticated/superadmin/nominations': typeof AuthenticatedSuperadminNominationsRoute
  '/_authenticated/superadmin/users': typeof AuthenticatedSuperadminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/rep/': typeof AuthenticatedRepIndexRoute
  '/_authenticated/runner/': typeof AuthenticatedRunnerIndexRoute
  '/_authenticated/superadmin/': typeof AuthenticatedSuperadminIndexRoute
  '/_authenticated/association/$slug/approvals': typeof AuthenticatedAssociationSlugApprovalsRoute
  '/_authenticated/association/$slug/audit': typeof AuthenticatedAssociationSlugAuditRoute
  '/_authenticated/association/$slug/bank': typeof AuthenticatedAssociationSlugBankRoute
  '/_authenticated/association/$slug/dues': typeof AuthenticatedAssociationSlugDuesRoute
  '/_authenticated/association/$slug/executives': typeof AuthenticatedAssociationSlugExecutivesRoute
  '/_authenticated/association/$slug/finance': typeof AuthenticatedAssociationSlugFinanceRoute
  '/_authenticated/association/$slug/members': typeof AuthenticatedAssociationSlugMembersRoute
  '/_authenticated/association/$slug/payment-links': typeof AuthenticatedAssociationSlugPaymentLinksRoute
  '/_authenticated/superadmin/association/$id': typeof AuthenticatedSuperadminAssociationIdRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/_authenticated/association/$slug/': typeof AuthenticatedAssociationSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/legal'
    | '/association-login'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/admin'
    | '/rep'
    | '/runner'
    | '/superadmin'
    | '/dashboard'
    | '/onboarding'
    | '/legal/association-verification'
    | '/legal/compliance'
    | '/legal/payment'
    | '/legal/privacy'
    | '/legal/qr-verification'
    | '/legal/refund'
    | '/legal/security'
    | '/legal/terms'
    | '/p/$token'
    | '/verify/$token'
    | '/associations/'
    | '/verify/'
    | '/association/$slug'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/faculties'
    | '/admin/page-health'
    | '/admin/payment-requests'
    | '/admin/qr-codes'
    | '/admin/reconcile'
    | '/admin/runners'
    | '/admin/settlements'
    | '/admin/students'
    | '/admin/transactions'
    | '/admin/users'
    | '/associations/new'
    | '/pay/$requestId'
    | '/receipt/$token'
    | '/superadmin/activity'
    | '/superadmin/associations'
    | '/superadmin/bank-verifications'
    | '/superadmin/nominations'
    | '/superadmin/users'
    | '/admin/'
    | '/rep/'
    | '/runner/'
    | '/superadmin/'
    | '/association/$slug/approvals'
    | '/association/$slug/audit'
    | '/association/$slug/bank'
    | '/association/$slug/dues'
    | '/association/$slug/executives'
    | '/association/$slug/finance'
    | '/association/$slug/members'
    | '/association/$slug/payment-links'
    | '/superadmin/association/$id'
    | '/api/public/webhooks/paystack'
    | '/association/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/legal'
    | '/association-login'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/dashboard'
    | '/onboarding'
    | '/legal/association-verification'
    | '/legal/compliance'
    | '/legal/payment'
    | '/legal/privacy'
    | '/legal/qr-verification'
    | '/legal/refund'
    | '/legal/security'
    | '/legal/terms'
    | '/p/$token'
    | '/verify/$token'
    | '/associations'
    | '/verify'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/faculties'
    | '/admin/page-health'
    | '/admin/payment-requests'
    | '/admin/qr-codes'
    | '/admin/reconcile'
    | '/admin/runners'
    | '/admin/settlements'
    | '/admin/students'
    | '/admin/transactions'
    | '/admin/users'
    | '/associations/new'
    | '/pay/$requestId'
    | '/receipt/$token'
    | '/superadmin/activity'
    | '/superadmin/associations'
    | '/superadmin/bank-verifications'
    | '/superadmin/nominations'
    | '/superadmin/users'
    | '/admin'
    | '/rep'
    | '/runner'
    | '/superadmin'
    | '/association/$slug/approvals'
    | '/association/$slug/audit'
    | '/association/$slug/bank'
    | '/association/$slug/dues'
    | '/association/$slug/executives'
    | '/association/$slug/finance'
    | '/association/$slug/members'
    | '/association/$slug/payment-links'
    | '/superadmin/association/$id'
    | '/api/public/webhooks/paystack'
    | '/association/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/legal'
    | '/association-login'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/rep'
    | '/_authenticated/runner'
    | '/_authenticated/superadmin'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/legal/association-verification'
    | '/legal/compliance'
    | '/legal/payment'
    | '/legal/privacy'
    | '/legal/qr-verification'
    | '/legal/refund'
    | '/legal/security'
    | '/legal/terms'
    | '/p/$token'
    | '/verify/$token'
    | '/associations/'
    | '/verify/'
    | '/_authenticated/association/$slug'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/faculties'
    | '/_authenticated/admin/page-health'
    | '/_authenticated/admin/payment-requests'
    | '/_authenticated/admin/qr-codes'
    | '/_authenticated/admin/reconcile'
    | '/_authenticated/admin/runners'
    | '/_authenticated/admin/settlements'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/transactions'
    | '/_authenticated/admin/users'
    | '/_authenticated/associations/new'
    | '/_authenticated/pay/$requestId'
    | '/_authenticated/receipt/$token'
    | '/_authenticated/superadmin/activity'
    | '/_authenticated/superadmin/associations'
    | '/_authenticated/superadmin/bank-verifications'
    | '/_authenticated/superadmin/nominations'
    | '/_authenticated/superadmin/users'
    | '/_authenticated/admin/'
    | '/_authenticated/rep/'
    | '/_authenticated/runner/'
    | '/_authenticated/superadmin/'
    | '/_authenticated/association/$slug/approvals'
    | '/_authenticated/association/$slug/audit'
    | '/_authenticated/association/$slug/bank'
    | '/_authenticated/association/$slug/dues'
    | '/_authenticated/association/$slug/executives'
    | '/_authenticated/association/$slug/finance'
    | '/_authenticated/association/$slug/members'
    | '/_authenticated/association/$slug/payment-links'
    | '/_authenticated/superadmin/association/$id'
    | '/api/public/webhooks/paystack'
    | '/_authenticated/association/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LegalRouteRoute: typeof LegalRouteRouteWithChildren
  AssociationLoginRoute: typeof AssociationLoginRoute
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PTokenRoute: typeof PTokenRoute
  VerifyTokenRoute: typeof VerifyTokenRoute
  AssociationsIndexRoute: typeof AssociationsIndexRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/association-login': {
      id: '/association-login'
      path: '/association-login'
      fullPath: '/association-login'
      preLoaderRoute: typeof AssociationLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rep': {
      id: '/_authenticated/rep'
      path: '/rep'
      fullPath: '/rep'
      preLoaderRoute: typeof AuthenticatedRepRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/runner': {
      id: '/_authenticated/runner'
      path: '/runner'
      fullPath: '/runner'
      preLoaderRoute: typeof AuthenticatedRunnerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/superadmin': {
      id: '/_authenticated/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof AuthenticatedSuperadminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/associations/': {
      id: '/associations/'
      path: '/associations'
      fullPath: '/associations/'
      preLoaderRoute: typeof AssociationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/association-verification': {
      id: '/legal/association-verification'
      path: '/association-verification'
      fullPath: '/legal/association-verification'
      preLoaderRoute: typeof LegalAssociationVerificationRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/compliance': {
      id: '/legal/compliance'
      path: '/compliance'
      fullPath: '/legal/compliance'
      preLoaderRoute: typeof LegalComplianceRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/payment': {
      id: '/legal/payment'
      path: '/payment'
      fullPath: '/legal/payment'
      preLoaderRoute: typeof LegalPaymentRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/qr-verification': {
      id: '/legal/qr-verification'
      path: '/qr-verification'
      fullPath: '/legal/qr-verification'
      preLoaderRoute: typeof LegalQrVerificationRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/security': {
      id: '/legal/security'
      path: '/security'
      fullPath: '/legal/security'
      preLoaderRoute: typeof LegalSecurityRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/faculties': {
      id: '/_authenticated/admin/faculties'
      path: '/faculties'
      fullPath: '/admin/faculties'
      preLoaderRoute: typeof AuthenticatedAdminFacultiesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/page-health': {
      id: '/_authenticated/admin/page-health'
      path: '/page-health'
      fullPath: '/admin/page-health'
      preLoaderRoute: typeof AuthenticatedAdminPageHealthRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payment-requests': {
      id: '/_authenticated/admin/payment-requests'
      path: '/payment-requests'
      fullPath: '/admin/payment-requests'
      preLoaderRoute: typeof AuthenticatedAdminPaymentRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/qr-codes': {
      id: '/_authenticated/admin/qr-codes'
      path: '/qr-codes'
      fullPath: '/admin/qr-codes'
      preLoaderRoute: typeof AuthenticatedAdminQrCodesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reconcile': {
      id: '/_authenticated/admin/reconcile'
      path: '/reconcile'
      fullPath: '/admin/reconcile'
      preLoaderRoute: typeof AuthenticatedAdminReconcileRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/runners': {
      id: '/_authenticated/admin/runners'
      path: '/runners'
      fullPath: '/admin/runners'
      preLoaderRoute: typeof AuthenticatedAdminRunnersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settlements': {
      id: '/_authenticated/admin/settlements'
      path: '/settlements'
      fullPath: '/admin/settlements'
      preLoaderRoute: typeof AuthenticatedAdminSettlementsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/transactions': {
      id: '/_authenticated/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AuthenticatedAdminTransactionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/association/$slug': {
      id: '/_authenticated/association/$slug'
      path: '/association/$slug'
      fullPath: '/association/$slug'
      preLoaderRoute: typeof AuthenticatedAssociationSlugRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/associations/new': {
      id: '/_authenticated/associations/new'
      path: '/associations/new'
      fullPath: '/associations/new'
      preLoaderRoute: typeof AuthenticatedAssociationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pay/$requestId': {
      id: '/_authenticated/pay/$requestId'
      path: '/pay/$requestId'
      fullPath: '/pay/$requestId'
      preLoaderRoute: typeof AuthenticatedPayRequestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receipt/$token': {
      id: '/_authenticated/receipt/$token'
      path: '/receipt/$token'
      fullPath: '/receipt/$token'
      preLoaderRoute: typeof AuthenticatedReceiptTokenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rep/': {
      id: '/_authenticated/rep/'
      path: '/'
      fullPath: '/rep/'
      preLoaderRoute: typeof AuthenticatedRepIndexRouteImport
      parentRoute: typeof AuthenticatedRepRouteRoute
    }
    '/_authenticated/runner/': {
      id: '/_authenticated/runner/'
      path: '/'
      fullPath: '/runner/'
      preLoaderRoute: typeof AuthenticatedRunnerIndexRouteImport
      parentRoute: typeof AuthenticatedRunnerRouteRoute
    }
    '/_authenticated/superadmin/': {
      id: '/_authenticated/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof AuthenticatedSuperadminIndexRouteImport
      parentRoute: typeof AuthenticatedSuperadminRouteRoute
    }
    '/_authenticated/superadmin/activity': {
      id: '/_authenticated/superadmin/activity'
      path: '/activity'
      fullPath: '/superadmin/activity'
      preLoaderRoute: typeof AuthenticatedSuperadminActivityRouteImport
      parentRoute: typeof AuthenticatedSuperadminRouteRoute
    }
    '/_authenticated/superadmin/associations': {
      id: '/_authenticated/superadmin/associations'
      path: '/associations'
      fullPath: '/superadmin/associations'
      preLoaderRoute: typeof AuthenticatedSuperadminAssociationsRouteImport
      parentRoute: typeof AuthenticatedSuperadminRouteRoute
    }
    '/_authenticated/superadmin/bank-verifications': {
      id: '/_authenticated/superadmin/bank-verifications'
      path: '/bank-verifications'
      fullPath: '/superadmin/bank-verifications'
      preLoaderRoute: typeof AuthenticatedSuperadminBankVerificationsRouteImport
      parentRoute: typeof AuthenticatedSuperadminRouteRoute
    }
    '/_authenticated/superadmin/nominations': {
      id: '/_authenticated/superadmin/nominations'
      path: '/nominations'
      fullPath: '/superadmin/nominations'
      preLoaderRoute: typeof AuthenticatedSuperadminNominationsRouteImport
      parentRoute: typeof AuthenticatedSuperadminRouteRoute
    }
    '/_authenticated/superadmin/users': {
      id: '/_authenticated/superadmin/users'
      path: '/users'
      fullPath: '/superadmin/users'
      preLoaderRoute: typeof AuthenticatedSuperadminUsersRouteImport
      parentRoute: typeof AuthenticatedSuperadminRouteRoute
    }
    '/_authenticated/association/$slug/': {
      id: '/_authenticated/association/$slug/'
      path: '/'
      fullPath: '/association/$slug/'
      preLoaderRoute: typeof AuthenticatedAssociationSlugIndexRouteImport
      parentRoute: typeof AuthenticatedAssociationSlugRouteRoute
    }
    '/_authenticated/association/$slug/approvals': {
      id: '/_authenticated/association/$slug/approvals'
      path: '/approvals'
      fullPath: '/association/$slug/approvals'
      preLoaderRoute: typeof AuthenticatedAssociationSlugApprovalsRouteImport
      parentRoute: typeof AuthenticatedAssociationSlugRouteRoute
    }
    '/_authenticated/association/$slug/audit': {
      id: '/_authenticated/association/$slug/audit'
      path: '/audit'
      fullPath: '/association/$slug/audit'
      preLoaderRoute: typeof AuthenticatedAssociationSlugAuditRouteImport
      parentRoute: typeof AuthenticatedAssociationSlugRouteRoute
    }
    '/_authenticated/association/$slug/bank': {
      id: '/_authenticated/association/$slug/bank'
      path: '/bank'
      fullPath: '/association/$slug/bank'
      preLoaderRoute: typeof AuthenticatedAssociationSlugBankRouteImport
      parentRoute: typeof AuthenticatedAssociationSlugRouteRoute
    }
    '/_authenticated/association/$slug/dues': {
      id: '/_authenticated/association/$slug/dues'
      path: '/dues'
      fullPath: '/association/$slug/dues'
      preLoaderRoute: typeof AuthenticatedAssociationSlugDuesRouteImport
      parentRoute: typeof AuthenticatedAssociationSlugRouteRoute
    }
    '/_authenticated/association/$slug/executives': {
      id: '/_authenticated/association/$slug/executives'
      path: '/executives'
      fullPath: '/association/$slug/executives'
      preLoaderRoute: typeof AuthenticatedAssociationSlugExecutivesRouteImport
      parentRoute: typeof AuthenticatedAssociationSlugRouteRoute
    }
    '/_authenticated/association/$slug/finance': {
      id: '/_authenticated/association/$slug/finance'
      path: '/finance'
      fullPath: '/association/$slug/finance'
      preLoaderRoute: typeof AuthenticatedAssociationSlugFinanceRouteImport
      parentRoute: typeof AuthenticatedAssociationSlugRouteRoute
    }
    '/_authenticated/association/$slug/members': {
      id: '/_authenticated/association/$slug/members'
      path: '/members'
      fullPath: '/association/$slug/members'
      preLoaderRoute: typeof AuthenticatedAssociationSlugMembersRouteImport
      parentRoute: typeof AuthenticatedAssociationSlugRouteRoute
    }
    '/_authenticated/association/$slug/payment-links': {
      id: '/_authenticated/association/$slug/payment-links'
      path: '/payment-links'
      fullPath: '/association/$slug/payment-links'
      preLoaderRoute: typeof AuthenticatedAssociationSlugPaymentLinksRouteImport
      parentRoute: typeof AuthenticatedAssociationSlugRouteRoute
    }
    '/_authenticated/superadmin/association/$id': {
      id: '/_authenticated/superadmin/association/$id'
      path: '/association/$id'
      fullPath: '/superadmin/association/$id'
      preLoaderRoute: typeof AuthenticatedSuperadminAssociationIdRouteImport
      parentRoute: typeof AuthenticatedSuperadminRouteRoute
    }
    '/api/public/webhooks/paystack': {
      id: '/api/public/webhooks/paystack'
      path: '/api/public/webhooks/paystack'
      fullPath: '/api/public/webhooks/paystack'
      preLoaderRoute: typeof ApiPublicWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminFacultiesRoute: typeof AuthenticatedAdminFacultiesRoute
  AuthenticatedAdminPageHealthRoute: typeof AuthenticatedAdminPageHealthRoute
  AuthenticatedAdminPaymentRequestsRoute: typeof AuthenticatedAdminPaymentRequestsRoute
  AuthenticatedAdminQrCodesRoute: typeof AuthenticatedAdminQrCodesRoute
  AuthenticatedAdminReconcileRoute: typeof AuthenticatedAdminReconcileRoute
  AuthenticatedAdminRunnersRoute: typeof AuthenticatedAdminRunnersRoute
  AuthenticatedAdminSettlementsRoute: typeof AuthenticatedAdminSettlementsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminTransactionsRoute: typeof AuthenticatedAdminTransactionsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminFacultiesRoute: AuthenticatedAdminFacultiesRoute,
    AuthenticatedAdminPageHealthRoute: AuthenticatedAdminPageHealthRoute,
    AuthenticatedAdminPaymentRequestsRoute:
      AuthenticatedAdminPaymentRequestsRoute,
    AuthenticatedAdminQrCodesRoute: AuthenticatedAdminQrCodesRoute,
    AuthenticatedAdminReconcileRoute: AuthenticatedAdminReconcileRoute,
    AuthenticatedAdminRunnersRoute: AuthenticatedAdminRunnersRoute,
    AuthenticatedAdminSettlementsRoute: AuthenticatedAdminSettlementsRoute,
    AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
    AuthenticatedAdminTransactionsRoute: AuthenticatedAdminTransactionsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRepRouteRouteChildren {
  AuthenticatedRepIndexRoute: typeof AuthenticatedRepIndexRoute
}

const AuthenticatedRepRouteRouteChildren: AuthenticatedRepRouteRouteChildren = {
  AuthenticatedRepIndexRoute: AuthenticatedRepIndexRoute,
}

const AuthenticatedRepRouteRouteWithChildren =
  AuthenticatedRepRouteRoute._addFileChildren(
    AuthenticatedRepRouteRouteChildren,
  )

interface AuthenticatedRunnerRouteRouteChildren {
  AuthenticatedRunnerIndexRoute: typeof AuthenticatedRunnerIndexRoute
}

const AuthenticatedRunnerRouteRouteChildren: AuthenticatedRunnerRouteRouteChildren =
  {
    AuthenticatedRunnerIndexRoute: AuthenticatedRunnerIndexRoute,
  }

const AuthenticatedRunnerRouteRouteWithChildren =
  AuthenticatedRunnerRouteRoute._addFileChildren(
    AuthenticatedRunnerRouteRouteChildren,
  )

interface AuthenticatedSuperadminRouteRouteChildren {
  AuthenticatedSuperadminActivityRoute: typeof AuthenticatedSuperadminActivityRoute
  AuthenticatedSuperadminAssociationsRoute: typeof AuthenticatedSuperadminAssociationsRoute
  AuthenticatedSuperadminBankVerificationsRoute: typeof AuthenticatedSuperadminBankVerificationsRoute
  AuthenticatedSuperadminNominationsRoute: typeof AuthenticatedSuperadminNominationsRoute
  AuthenticatedSuperadminUsersRoute: typeof AuthenticatedSuperadminUsersRoute
  AuthenticatedSuperadminIndexRoute: typeof AuthenticatedSuperadminIndexRoute
  AuthenticatedSuperadminAssociationIdRoute: typeof AuthenticatedSuperadminAssociationIdRoute
}

const AuthenticatedSuperadminRouteRouteChildren: AuthenticatedSuperadminRouteRouteChildren =
  {
    AuthenticatedSuperadminActivityRoute: AuthenticatedSuperadminActivityRoute,
    AuthenticatedSuperadminAssociationsRoute:
      AuthenticatedSuperadminAssociationsRoute,
    AuthenticatedSuperadminBankVerificationsRoute:
      AuthenticatedSuperadminBankVerificationsRoute,
    AuthenticatedSuperadminNominationsRoute:
      AuthenticatedSuperadminNominationsRoute,
    AuthenticatedSuperadminUsersRoute: AuthenticatedSuperadminUsersRoute,
    AuthenticatedSuperadminIndexRoute: AuthenticatedSuperadminIndexRoute,
    AuthenticatedSuperadminAssociationIdRoute:
      AuthenticatedSuperadminAssociationIdRoute,
  }

const AuthenticatedSuperadminRouteRouteWithChildren =
  AuthenticatedSuperadminRouteRoute._addFileChildren(
    AuthenticatedSuperadminRouteRouteChildren,
  )

interface AuthenticatedAssociationSlugRouteRouteChildren {
  AuthenticatedAssociationSlugApprovalsRoute: typeof AuthenticatedAssociationSlugApprovalsRoute
  AuthenticatedAssociationSlugAuditRoute: typeof AuthenticatedAssociationSlugAuditRoute
  AuthenticatedAssociationSlugBankRoute: typeof AuthenticatedAssociationSlugBankRoute
  AuthenticatedAssociationSlugDuesRoute: typeof AuthenticatedAssociationSlugDuesRoute
  AuthenticatedAssociationSlugExecutivesRoute: typeof AuthenticatedAssociationSlugExecutivesRoute
  AuthenticatedAssociationSlugFinanceRoute: typeof AuthenticatedAssociationSlugFinanceRoute
  AuthenticatedAssociationSlugMembersRoute: typeof AuthenticatedAssociationSlugMembersRoute
  AuthenticatedAssociationSlugPaymentLinksRoute: typeof AuthenticatedAssociationSlugPaymentLinksRoute
  AuthenticatedAssociationSlugIndexRoute: typeof AuthenticatedAssociationSlugIndexRoute
}

const AuthenticatedAssociationSlugRouteRouteChildren: AuthenticatedAssociationSlugRouteRouteChildren =
  {
    AuthenticatedAssociationSlugApprovalsRoute:
      AuthenticatedAssociationSlugApprovalsRoute,
    AuthenticatedAssociationSlugAuditRoute:
      AuthenticatedAssociationSlugAuditRoute,
    AuthenticatedAssociationSlugBankRoute:
      AuthenticatedAssociationSlugBankRoute,
    AuthenticatedAssociationSlugDuesRoute:
      AuthenticatedAssociationSlugDuesRoute,
    AuthenticatedAssociationSlugExecutivesRoute:
      AuthenticatedAssociationSlugExecutivesRoute,
    AuthenticatedAssociationSlugFinanceRoute:
      AuthenticatedAssociationSlugFinanceRoute,
    AuthenticatedAssociationSlugMembersRoute:
      AuthenticatedAssociationSlugMembersRoute,
    AuthenticatedAssociationSlugPaymentLinksRoute:
      AuthenticatedAssociationSlugPaymentLinksRoute,
    AuthenticatedAssociationSlugIndexRoute:
      AuthenticatedAssociationSlugIndexRoute,
  }

const AuthenticatedAssociationSlugRouteRouteWithChildren =
  AuthenticatedAssociationSlugRouteRoute._addFileChildren(
    AuthenticatedAssociationSlugRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedRepRouteRoute: typeof AuthenticatedRepRouteRouteWithChildren
  AuthenticatedRunnerRouteRoute: typeof AuthenticatedRunnerRouteRouteWithChildren
  AuthenticatedSuperadminRouteRoute: typeof AuthenticatedSuperadminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedAssociationSlugRouteRoute: typeof AuthenticatedAssociationSlugRouteRouteWithChildren
  AuthenticatedAssociationsNewRoute: typeof AuthenticatedAssociationsNewRoute
  AuthenticatedPayRequestIdRoute: typeof AuthenticatedPayRequestIdRoute
  AuthenticatedReceiptTokenRoute: typeof AuthenticatedReceiptTokenRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedRepRouteRoute: AuthenticatedRepRouteRouteWithChildren,
  AuthenticatedRunnerRouteRoute: AuthenticatedRunnerRouteRouteWithChildren,
  AuthenticatedSuperadminRouteRoute:
    AuthenticatedSuperadminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedAssociationSlugRouteRoute:
    AuthenticatedAssociationSlugRouteRouteWithChildren,
  AuthenticatedAssociationsNewRoute: AuthenticatedAssociationsNewRoute,
  AuthenticatedPayRequestIdRoute: AuthenticatedPayRequestIdRoute,
  AuthenticatedReceiptTokenRoute: AuthenticatedReceiptTokenRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LegalRouteRouteChildren {
  LegalAssociationVerificationRoute: typeof LegalAssociationVerificationRoute
  LegalComplianceRoute: typeof LegalComplianceRoute
  LegalPaymentRoute: typeof LegalPaymentRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalQrVerificationRoute: typeof LegalQrVerificationRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalSecurityRoute: typeof LegalSecurityRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteRouteChildren: LegalRouteRouteChildren = {
  LegalAssociationVerificationRoute: LegalAssociationVerificationRoute,
  LegalComplianceRoute: LegalComplianceRoute,
  LegalPaymentRoute: LegalPaymentRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalQrVerificationRoute: LegalQrVerificationRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalSecurityRoute: LegalSecurityRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteRouteWithChildren = LegalRouteRoute._addFileChildren(
  LegalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LegalRouteRoute: LegalRouteRouteWithChildren,
  AssociationLoginRoute: AssociationLoginRoute,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PTokenRoute: PTokenRoute,
  VerifyTokenRoute: VerifyTokenRoute,
  AssociationsIndexRoute: AssociationsIndexRoute,
  VerifyIndexRoute: VerifyIndexRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
